sudo: false
language: node_js
node_js:
- '5.0'
env:
  global:
  - SAUCE_USERNAME: fine-uploader-wrap
  - secure: eL/a9BXVfxleliC99O4b1qpF/ZXfbjaMFZK0VAxAgapZ9NXzUXw6ynX0OgRAimj65PFSbIufEEETi1zanz9PXuqM64Gpk4AEsembELAL3m7Am42RDNMOSj79EA8TNs798jdcvmYIQJSZ0YF3bAobIXVAIgoY6JYgmqDAiJ2PSRSO/AyK7M67y60lBzi9wuf1OEvCkIHazWsDcZ29k5rvWNRjPK3ex2YUgj3rqRheryPMPunscZAwx8GaeWkG20DseubPMLjP4JVLAhx0LbxajQy2zuY438VIkousUyIfBrMlYEINBL6SXbWTgibb9CQIzXtI8abnh1KdHNOeJw55vOUkq3iOCpkfcOuIc0d33Uf934mqNBxKIp1tG8OHtnJCNkqFiQmjQGn0CFxBN/CTiPDY88pWoast9fw4n0jo2BIYcMpwxmOoMAJJJ7wcziGbEZV5LUtJSpd0gGqrQESz6xLcos61KBePcnsbcCsvWW31jzXOFjWuWW+Fe+8LbPfvEJ1gk44XDkepDHY3VFieGdU3Hiwh8ge5LIJ2WzijC7cwxed7Gp/Wa+AA/fxs28q7nqf4cPzTfDKW2ijEVSONBKH5hKbxtth+JRnz3mdu7r+RGw+ov62ive2/B4M7Vpi8kds5hAVy7Monjjnw7eO39DfXmy26IxNq/BF+WrZcUjA=
